F3DEX3: cpu/occlusionplane.c File Reference
occlusionplane.c File Reference
Functions
s16 FloatToS16Clamp (float f)
s16 FloatMinus1To1ToS16 (float f)
void ClipToScreenSpace (PlayState *play, const Vec3f *clipXYZ, float clipW, Vec2f *screen)
bool ClipPolygon (PlayState *play, ClipVertex *verts, s8 *indices, s8 **idxFinalStart, s8 **idxFinalEnd)
OcclusionPlane * ComputeOcclusionPlane (PlayState *play, Vec3f *worldBounds)
void someDrawFunction (PlayState *play)
Variables
static OcclusionPlane sNoOcclusionPlane
Function Documentation
ClipPolygon()
bool ClipPolygon (PlayState * play, ClipVertex * verts, s8 * indices, s8 ** idxFinalStart, s8 ** idxFinalEnd)
References ClipToScreenSpace().
ClipToScreenSpace()
void ClipToScreenSpace (PlayState * play, const Vec3f * clipXYZ, float clipW, Vec2f * screen)
ComputeOcclusionPlane()
OcclusionPlane * ComputeOcclusionPlane (PlayState * play, Vec3f * worldBounds)
References ClipPolygon(), ClipToScreenSpace(), FloatMinus1To1ToS16(), and sNoOcclusionPlane.
FloatMinus1To1ToS16()
s16 FloatMinus1To1ToS16 (float f)
References FloatToS16Clamp().
FloatToS16Clamp()
s16 FloatToS16Clamp (float f)
someDrawFunction()
void someDrawFunction (PlayState * play)
References ComputeOcclusionPlane().
Variable Documentation
sNoOcclusionPlane
OcclusionPlane sNoOcclusionPlane static
Initial value:
= {
    0x0000,
    0x0000,
    0x0000,
    0x0000,
    0x8000,
    0x8000,
    0x8000,
    0x8000,
    0x0000,
    0x0000,
    0x0000,
    0x8000
}