var searchData=
[
  ['c_20gbi_20compatibility_0',['C GBI Compatibility',['../compatibility.html#autotoc_md10',1,'']]],
  ['camera_1',['Camera',['../camera.html',1,'md_docs_2code']]],
  ['camera_2emd_2',['Camera.md',['../Camera_8md.html',1,'']]],
  ['changes_3',['Required Changes',['../porting.html#autotoc_md30',1,'']]],
  ['changes_20lighting_4',['Recommended Changes (Lighting)',['../porting.html#autotoc_md32',1,'']]],
  ['changes_20non_20lighting_5',['Recommended Changes (Non-Lighting)',['../porting.html#autotoc_md31',1,'']]],
  ['changes_20required_20for_20new_20features_6',['Changes Required for New Features',['../porting.html#autotoc_md33',1,'']]],
  ['clipping_20minimal_20scanlines_20algorithm_7',['clipping minimal scanlines algorithm',['../minimal-scanlines.html',1,'What happened to the clipping minimal scanlines algorithm?'],['../minimal-scanlines.html#autotoc_md27',1,'What happened to the clipping minimal scanlines algorithm?']]],
  ['clipping_20removal_8',['Far clipping removal',['../design-tradeoffs.html#autotoc_md22',1,'']]],
  ['clippolygon_9',['ClipPolygon',['../occlusionplane_8c.html#a9d47fcdd39f1d317f634fcc8bd57aafd',1,'occlusionplane.c']]],
  ['cliptoscreenspace_10',['ClipToScreenSpace',['../occlusionplane_8c.html#a7590e134ab63d47c9c3035cfd16c0a9b',1,'occlusionplane.c']]],
  ['code_11',['Code',['../md_docs_2code.html',1,'']]],
  ['code_20size_12',['Optimizing for RSP code size',['../design-tradeoffs.html#autotoc_md21',1,'']]],
  ['code_2emd_13',['code.md',['../code_8md.html',1,'']]],
  ['codebase_20to_20f3dex3_14',['Codebase to F3DEX3',['../porting.html',1,'Porting Your Romhack Codebase to F3DEX3'],['../porting.html#autotoc_md29',1,'Porting Your Romhack Codebase to F3DEX3']]],
  ['compatibility_15',['Compatibility',['../compatibility.html#autotoc_md11',1,'Binary Display List Compatibility'],['../compatibility.html#autotoc_md10',1,'C GBI Compatibility']]],
  ['compatibility_20with_20f3dex2_16',['Compatibility with F3DEX2',['../compatibility.html',1,'Backwards Compatibility with F3DEX2'],['../compatibility.html#autotoc_md9',1,'Backwards Compatibility with F3DEX2']]],
  ['computeocclusionplane_17',['ComputeOcclusionPlane',['../occlusionplane_8c.html#a258c47ec4d3848c48875e8703899da68',1,'occlusionplane.c']]],
  ['configuration_18',['Configuration',['../microcode.html',1,'Microcode Configuration'],['../microcode.html#autotoc_md12',1,'Microcode Configuration']]],
  ['configuration_2emd_19',['Configuration.md',['../Configuration_8md.html',1,'']]],
  ['counters_20',['Performance Counters',['../counters.html',1,'md_docs_2code']]],
  ['counters_2emd_21',['Counters.md',['../Counters_8md.html',1,'']]],
  ['credits_22',['Credits',['../md_README.html#autotoc_md6',1,'']]]
];
