var searchData=
[
  ['tc_0',['tc',['../structVtx__t.html#a2020b066452aa4c208b26c8b68c4d056',1,'Vtx_t::tc'],['../structVtx__tn.html#a2020b066452aa4c208b26c8b68c4d056',1,'Vtx_tn::tc']]],
  ['temporary_20buffers_20shrinking_1',['RDP temporary buffers shrinking',['../design-tradeoffs.html#autotoc_md33',1,'']]],
  ['texrect_2',['TexRect',['../structTexRect.html',1,'']]],
  ['textured_20tris_3',['Non-textured tris',['../design-tradeoffs.html#autotoc_md35',1,'']]],
  ['that_20should_20never_20matter_20in_20practice_4',['Obscure semantic differences from F3DEX2 that should never matter in practice',['../design-tradeoffs.html#autotoc_md36',1,'']]],
  ['the_20tradeoffs_20for_20all_20these_20new_20features_5',['What are the tradeoffs for all these new features?',['../design-tradeoffs.html#autotoc_md28',1,'']]],
  ['these_20new_20features_6',['What are the tradeoffs for all these new features?',['../design-tradeoffs.html#autotoc_md28',1,'']]],
  ['time_20for_20occlusion_20plane_7',['Vertex processing RSP time for occlusion plane',['../design-tradeoffs.html#autotoc_md29',1,'']]],
  ['tiny3d_8',['Comparison with Tiny3D',['../snake.html#autotoc_md53',1,'']]],
  ['to_20f3dex3_9',['to F3DEX3',['../porting.html',1,'Porting Your Romhack Codebase to F3DEX3'],['../porting.html#autotoc_md39',1,'Porting Your Romhack Codebase to F3DEX3']]],
  ['tradeoffs_10',['Design Tradeoffs',['../design-tradeoffs.html',1,'md_docs_2documentation']]],
  ['tradeoffs_20for_20all_20these_20new_20features_11',['What are the tradeoffs for all these new features?',['../design-tradeoffs.html#autotoc_md28',1,'']]],
  ['tri_12',['Tri',['../structTri.html',1,'']]],
  ['triangle_20snake_13',['Triangle Snake',['../snake.html',1,'md_docs_2documentation']]],
  ['tris_14',['Non-textured tris',['../design-tradeoffs.html#autotoc_md35',1,'']]],
  ['tt_15',['tt',['../removed.html#autotoc_md49',1,'&lt;tt&gt;SPTriStrip&lt;/tt&gt; and &lt;tt&gt;SPTriFan&lt;/tt&gt;'],['../configuration.html#autotoc_md26',1,'Branch Depth Instruction (&lt;tt&gt;BrZ&lt;/tt&gt; / &lt;tt&gt;BrW&lt;/tt&gt;)'],['../configuration.html#autotoc_md27',1,'Debug Normals (&lt;tt&gt;dbgN&lt;/tt&gt;)']]],
  ['tt_20and_20tt_20sptrifan_20tt_16',['&lt;tt&gt;SPTriStrip&lt;/tt&gt; and &lt;tt&gt;SPTriFan&lt;/tt&gt;',['../removed.html#autotoc_md49',1,'']]],
  ['tt_20brw_20tt_17',['Branch Depth Instruction (&lt;tt&gt;BrZ&lt;/tt&gt; / &lt;tt&gt;BrW&lt;/tt&gt;)',['../configuration.html#autotoc_md26',1,'']]],
  ['tt_20brz_20tt_20tt_20brw_20tt_18',['Branch Depth Instruction (&lt;tt&gt;BrZ&lt;/tt&gt; / &lt;tt&gt;BrW&lt;/tt&gt;)',['../configuration.html#autotoc_md26',1,'']]],
  ['tt_20dbgn_20tt_19',['Debug Normals (&lt;tt&gt;dbgN&lt;/tt&gt;)',['../configuration.html#autotoc_md27',1,'']]],
  ['tt_20sptrifan_20tt_20',['&lt;tt&gt;SPTriStrip&lt;/tt&gt; and &lt;tt&gt;SPTriFan&lt;/tt&gt;',['../removed.html#autotoc_md49',1,'']]],
  ['tt_20sptristrip_20tt_20and_20tt_20sptrifan_20tt_21',['&lt;tt&gt;SPTriStrip&lt;/tt&gt; and &lt;tt&gt;SPTriFan&lt;/tt&gt;',['../removed.html#autotoc_md49',1,'']]],
  ['tt_20tt_20brw_20tt_22',['Branch Depth Instruction (&lt;tt&gt;BrZ&lt;/tt&gt; / &lt;tt&gt;BrW&lt;/tt&gt;)',['../configuration.html#autotoc_md26',1,'']]],
  ['type_23',['type',['../structLight__t.html#aa5044999f3339d2ba3b1bf22fa6cfe95',1,'Light_t']]]
];
