var searchData=
[
  ['cache_20locality_0',['Vertex Cache Locality',['../snake.html#autotoc_md53',1,'']]],
  ['camera_1',['Camera',['../camera.html',1,'md_docs_2code']]],
  ['changes_2',['Required Changes',['../porting.html#autotoc_md42',1,'']]],
  ['changes_20lighting_3',['Recommended Changes (Lighting)',['../porting.html#autotoc_md44',1,'']]],
  ['changes_20non_20lighting_4',['Recommended Changes (Non-Lighting)',['../porting.html#autotoc_md43',1,'']]],
  ['changes_20reference_5',['GBI Changes Reference',['../compatibility.html#autotoc_md15',1,'']]],
  ['changes_20required_20for_20new_20features_6',['Changes Required for New Features',['../porting.html#autotoc_md45',1,'']]],
  ['check_20timing_7',['Yield check timing',['../design-tradeoffs.html#autotoc_md36',1,'']]],
  ['clipping_20minimal_20scanlines_20algorithm_8',['Clipping minimal scanlines algorithm',['../removed.html#autotoc_md49',1,'']]],
  ['clipping_20removal_9',['Far clipping removal',['../design-tradeoffs.html#autotoc_md31',1,'']]],
  ['cn_10',['cn',['../structVtx__t.html#ac6d2aff53d0bd3fdfe97ac50bfff34e2',1,'Vtx_t']]],
  ['code_11',['Code',['../md_docs_2code.html',1,'']]],
  ['codebase_20to_20f3dex3_12',['Codebase to F3DEX3',['../porting.html',1,'Porting Your Romhack Codebase to F3DEX3'],['../porting.html#autotoc_md41',1,'Porting Your Romhack Codebase to F3DEX3']]],
  ['colc_13',['colc',['../structLight__t.html#a777970fc9405076cf854e6695d89b4c4',1,'Light_t::colc'],['../structPointLight__t.html#a777970fc9405076cf854e6695d89b4c4',1,'PointLight_t::colc']]],
  ['commands_14',['RDP Commands',['../compatibility.html#autotoc_md16',1,'']]],
  ['comparison_20with_20tiny3d_15',['Comparison with Tiny3D',['../snake.html#autotoc_md55',1,'']]],
  ['compatibility_20with_20f3dex2_16',['Compatibility with F3DEX2',['../compatibility.html',1,'Backwards Compatibility with F3DEX2'],['../compatibility.html#autotoc_md14',1,'Backwards Compatibility with F3DEX2']]],
  ['configuration_17',['Configuration',['../removed.html#autotoc_md47',1,'Legacy Vertex Pipeline (LVP) Configuration'],['../configuration.html',1,'Microcode Configuration'],['../configuration.html#autotoc_md23',1,'Microcode Configuration']]],
  ['control_20logic_18',['Control Logic',['../compatibility.html#autotoc_md18',1,'']]],
  ['counters_19',['Performance Counters',['../counters.html',1,'md_docs_2code']]],
  ['counts_20',['Counts',['../performance.html#autotoc_md39',1,'Cycle Counts'],['../performance.html#autotoc_md40',1,'Triangle Snake Cycle Counts']]],
  ['credits_21',['Credits',['../md_README.html#autotoc_md11',1,'']]],
  ['cycle_20counts_22',['Cycle Counts',['../performance.html#autotoc_md39',1,'Cycle Counts'],['../performance.html#autotoc_md40',1,'Triangle Snake Cycle Counts']]]
];
